"""Added required tables

Revision ID: 0794b880d04a
Revises: d5f540524f29
Create Date: 2021-05-18 16:20:59.433188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0794b880d04a'
down_revision = 'd5f540524f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
